language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'create database TestSynaxisQuotes;' -U postgres
script:
  - npm install
  - npm run test
after_success:
  -npm run test:cov